stages:
  - build_and_push
  - deploy

variables:
  IMAGE_NAME: "my-note-app"
  IMAGE_TAG: "latest"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

build_and_push:
  stage: build_and_push
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "Building Docker image..."
    - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .

    - echo "Logging in to Docker Hub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    - echo "Tagging image..."
    - docker tag "$IMAGE_NAME:$IMAGE_TAG" "$DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG"

    - echo "Pushing image to Docker Hub..."
    - docker push "$DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG"
  only:
    - main

deploy:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "Deploying container..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker-compose down || true
    - docker-compose up -d
  only:
    - main
